### PR TITLE
fix(tests): improve tests and add DEVELOPMENT.md docs

### PR DESCRIPTION
**Pull request by robertsLando**

### CODE REVIEW

**Review by q0rban — APPROVED** [review]
Fantastic, thank you! This is very helpful. I'm not sure if it is just my setup, but running `node test/test.js host all` fails on my local with:

```
Error: Cannot find module '@yao-pkg/pkg-fetch/lib-es5/upload.js'
```

Choosing `only-npm` seems to bypass that error.

**Review by SonyK16 — APPROVED** [review]

**Comment by robertsLando** [comment]
@q0rban try to run `yarn` from root folder and try again

**Comment by robertsLando** [comment]
@igorklopov I would like to start improving tests as right now they are very slow. I'm wondering if you have some ideas about how them could be improved, I tried looking at them but some are so big and nested especially npm related ones

**Comment by igorklopov** [comment]
I think they can be parallelized. IIRC they don't overlap.

**Comment by robertsLando** [comment]
> I think they can be parallelized. IIRC they don't overlap.

I did a try on https://github.com/yao-pkg/pkg/pull/3 without success. Will try again now once I can reach a working state :)

**Comment by q0rban** [comment]
> I think they can be parallelized. IIRC they don't overlap.

I just tested this with a Makefile, and it fails almost immediately with concurrency of 4:

```make
# Possible values are nodeXX (e.g. node20), or "host" to use the host-installed
# node version. Defaults to "host".
TARGET ?= host

ALL_FLAVORS := $(patsubst test/%/main.js,%,$(wildcard test/**/main.js))
NO_NPM := $(filter-out test-79-npm%,$(ALL_FLAVORS))
ONLY_NPM := "test-42-fetch-all" "test-46-multi-arch" "test-46-multi-arch-2" "test-10-pnpm" "test-11-pnpm" "test-80-compression-node-opcua" "test-99-\#1135" "test-99-\#1191" "test-99-\#1192" "test-00-sea"

.PHONY: all
all: $(ALL_FLAVORS)

.PHONY: test-%
test-%:
	@if [[ -z "$(wildcard test/test-$(*)*/main.js)" ]]; then \
	  echo "Unable to find test/test-$(*)*/main.js)"; \
	  exit 1; \
	fi
	node test/test.js $(TARGET) $(@)

.PHONY: no-npm
no-npm:
	$(MAKE) $(NO_NPM)

.PHONY: only-npm
only-npm:
	$(MAKE) $(ONLY_NPM)


```

```
make --jobs 4
```

This fails with a complicated mess of errors ^^

However, this runs just fine:

```
make
```

**Comment by robertsLando** [comment]
I tried to spawn tests in parallel here: https://github.com/yao-pkg/pkg/pull/115

Seems no benefit at all, tried with different concurrency as well, they run but some are not consistent as pnpm doesn't support concurrent install, same for codesign (tests are failing almost always on macos)

**Review by SonyK16 — COMMENTED** [review]
Quando se trata de automação de testes, algumas ferramentas se destacam bastante. O Selenium é super popular, especialmente para testes de aplicações web, porque é flexível e suporta várias linguagens de programação. Se você está trabalhando com Java, o JUnit é uma escolha clássica para testes unitários, oferecendo uma integração suave com muitos ambientes de desenvolvimento.

**Comment by robertsLando** [comment]
@SonyK16 It's not clear to me how your comment could be helpful

**Comment by q0rban** [comment]
I think it's a bot / spam

**Comment by sonyPROplayerNEWaccount2nd** [comment]
He is a bot for sure

**Pull request merged**
